### PR TITLE
Avoid multiple hash lookups

### PR DESCRIPTION
**Pull request by nyurik**
This is a rework based on #72 - it removes many hash lookups and clones, and instead uses one struct to keep all the relevant data.  The #72 contains some of the changes this PR used to have, and it can be merged as is without waiting.

Note that until #72 is merged, this PR will continue to show all changes from both PRs

### CODE REVIEW

**Comment by nyurik** [comment]
Actually, I think this should be solved differently -- its weird to use a cloned String as a key, with constant lookups, where all you want is a ref to your own struct.  I created https://github.com/ChevyRay/crunch-rs/pull/5 - with it it should be far easier to do this in a cleaner way

**Comment by flother** [comment]
Sounds good — do you want to leave this PR open and wait for the upstream PR to be merged?

**Comment by nyurik** [comment]
I pushed a new revision that uses the proposed upstream change. I may submit another PR that adapts some of the non-breaking changes, but lets keep this open once upstream merges (and so that you can review it)

**Comment by nyurik** [comment]
Silly me, all this was possible to do without the upstream changes

**Comment by nyurik** [comment]
On top of it, it turns out the per-sheet pixel ratio was never used, removed

**Comment by nyurik** [comment]
@flother any thoughts? thx!

**Comment by flother** [comment]
As with #73, merging #72 has caused a trivial conflict

**Comment by nyurik** [comment]
rebased

**Pull request merged**
